### ISSUE TITLE
PhpParser\Parser\Multiple cannot implement PhpParser\Parser - it is not an interface

### ISSUE THREAD

**Issue by boyfromhell** [rainlab/forum-plugin#86]
When I give to answer
this error occurs:

`PhpParser\Parser\Multiple cannot implement PhpParser\Parser - it is not an interface`

```
namespace PhpParser\Parser;

use PhpParser\Error;
use PhpParser\Parser;

class Multiple implements Parser {
    /** @var Parser[] List of parsers to try, in order of preference */
    private $parsers;
    /** @var Error[] Errors collected during last parse */
    private $errors;

    /**
```

Event Log:

```
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'PhpParser\Parser\Multiple cannot implement PhpParser\Parser - it is not an interface' in /home/ubuntu/workspace/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php:8
Stack trace:
#0 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(131): Symfony\Component\Debug\Exception\FatalErrorException->__construct()
#1 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(116): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError()
#2 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(0): Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#3 /home/ubuntu/workspace/vendor/nikic/php-parser/lib/PhpParser/Autoloader.php(49): ()
#4 /home/ubuntu/workspace/vendor/jeremeamia/SuperClosure/src/Analyzer/AstAnalyzer.php(26): PhpParser\Autoloader::autoload()
#5 /home/ubuntu/workspace/vendor/jeremeamia/SuperClosure/src/Analyzer/AstAnalyzer.php(26): spl_autoload_call()
#6 /home/ubuntu/workspace/vendor/jeremeamia/SuperClosure/src/Analyzer/AstAnalyzer.php(136): PhpParser\ParserFactory->create()
#7 /home/ubuntu/workspace/vendor/jeremeamia/SuperClosure/src/Analyzer/AstAnalyzer.php(127): SuperClosure\Analyzer\AstAnalyzer->getParser()
#8 /home/ubuntu/workspace/vendor/jeremeamia/SuperClosure/src/Analyzer/AstAnalyzer.php(54): SuperClosure\Analyzer\AstAnalyzer->getFileAst()
#9 /home/ubuntu/workspace/vendor/jeremeamia/SuperClosure/src/Analyzer/AstAnalyzer.php(29): SuperClosure\Analyzer\AstAnalyzer->locateClosure()
#10 /home/ubuntu/workspace/vendor/jeremeamia/SuperClosure/src/Analyzer/ClosureAnalyzer.php(29): SuperClosure\Analyzer\AstAnalyzer->determineCode()
#11 /home/ubuntu/workspace/vendor/jeremeamia/SuperClosure/src/Serializer.php(117): SuperClosure\Analyzer\ClosureAnalyzer->analyze()
#12 /home/ubuntu/workspace/vendor/jeremeamia/SuperClosure/src/SerializableClosure.php(111): SuperClosure\Serializer->getData()
#13 /home/ubuntu/workspace/vendor/jeremeamia/SuperClosure/src/Serializer.php(68): SuperClosure\SerializableClosure->serialize()
#14 /home/ubuntu/workspace/vendor/jeremeamia/SuperClosure/src/Serializer.php(68): serialize()
#15 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(243): SuperClosure\Serializer->serialize()
#16 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(182): Illuminate\Mail\Mailer->buildQueueCallable()
#17 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(216): Illuminate\Mail\Mailer->queue()
#18 /home/ubuntu/workspace/plugins/rainlab/forum/models/TopicFollow.php(135): Illuminate\Support\Facades\Facade::__callStatic()
#19 /home/ubuntu/workspace/plugins/rainlab/forum/models/TopicFollow.php(135): Illuminate\Support\Facades\Mail::queue()
#20 /home/ubuntu/workspace/plugins/rainlab/forum/components/Topic.php(334): RainLab\Forum\Models\TopicFollow::sendNotifications()
#21 /home/ubuntu/workspace/modules/cms/classes/ComponentBase.php(166): RainLab\Forum\Components\Topic->onPost()
#22 /home/ubuntu/workspace/modules/cms/classes/Controller.php(712): Cms\Classes\ComponentBase->runAjaxHandler()
#23 /home/ubuntu/workspace/modules/cms/classes/Controller.php(342): Cms\Classes\Controller->runAjaxHandler()
#24 /home/ubuntu/workspace/modules/cms/classes/Controller.php(209): Cms\Classes\Controller->runPage()
#25 /home/ubuntu/workspace/modules/cms/classes/CmsController.php(48): Cms\Classes\Controller->run()
#26 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(246): Cms\Classes\CmsController->run()
#27 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(246): call_user_func_array:{/home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:246}()
#28 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(162): Illuminate\Routing\Controller->callAction()
#29 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(107): Illuminate\Routing\ControllerDispatcher->call()
#30 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}()
#31 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): call_user_func:{/home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:141}()
#32 /home/ubuntu/workspace/plugins/qub/clockwork/vendor/itsgoingd/clockwork/Clockwork/Support/Laravel/ClockworkMiddleware.php(42): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#33 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Clockwork\Support\Laravel\ClockworkMiddleware->handle()
#34 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(101): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#35 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(101): call_user_func:{/home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:101}()
#36 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(108): Illuminate\Pipeline\Pipeline->then()
#37 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(67): Illuminate\Routing\ControllerDispatcher->callWithinStack()
#38 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Routing/Route.php(204): Illuminate\Routing\ControllerDispatcher->dispatch()
#39 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Routing/Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher()
#40 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Routing/Router.php(701): Illuminate\Routing\Route->run()
#41 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#42 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): call_user_func:{/home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:141}()
#43 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(101): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#44 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(101): call_user_func:{/home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:101}()
#45 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\Pipeline\Pipeline->then()
#46 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Routing/Router.php(670): Illuminate\Routing\Router->runRouteWithinStack()
#47 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\Routing\Router->dispatchToRoute()
#48 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(214): Illuminate\Routing\Router->dispatch()
#49 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#50 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): call_user_func:{/home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:141}()
#51 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(55): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#52 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
#53 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(61): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#54 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Session\Middleware\StartSession->handle()
#55 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(36): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#56 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
#57 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(40): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#58 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Cookie\Middleware\EncryptCookies->handle()
#59 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(42): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#60 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle()
#61 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(101): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#62 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(101): call_user_func:{/home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:101}()
#63 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(115): Illuminate\Pipeline\Pipeline->then()
#64 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(84): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#65 /home/ubuntu/workspace/index.php(44): Illuminate\Foundation\Http\Kernel->handle()
#66 /home/ubuntu/workspace/index.php(0): {main}()
#67 {main}
```

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
